name: Java with Nexus Repository

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://repo.lumania.net
        username: admin
        password: ${{ secrets.password }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=net.lumania artifactId=economy version=1.1
        assets: extension=jar
        filename: ./target/economy-1.0.jar
