name: Deploy to Nexus Repository

on:
  push:
  schedule:
    - cron: "26 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn test
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://179.61.251.103:10680
        username: ${{ secrets.nxrm_user }}
        password: ${{ secrets.nxrm_password }}
        repository: maven-releases
        coordinates: groupId=net.lumania artifactId=economy
        assets: extension=jar
        filename: ./target/economy-1.1.jar
    
    
    
